language: java
jdk: openjdk11
os:
  - linux
  dist: bionic

branches:
  only:
  - dev
  - master
  - hamap_2019_11
  except:
  - new_master
script: scripts/build.sh
notifications:  
  email:  
    recipients:  
    - nuka@ebi.ac.uk  
    on_success: always  
    on_failure: always
