language: java
jdk: openjdk11
os:
  - linux
branches:
  only:
  - dev
  except:
  - master
script: cd core && mvn -q clean install
notifications:  
  email:  
    recipients:  
    - nuka@ebi.ac.uk  
    on_success: always  
    on_failure: always
